### ISSUE TITLE
OrientDB version 2.1.3 with the latest orientjs fails to run transactions

### ISSUE THREAD

**Issue by alpeshgaglani** [orientechnologies/orientjs#102]
HI,
I just upgraded to the latest version of orientdb and orientjs. However, a bunch of scenarios related to updating embedded documents are now failing. Here's what I see in the logs:

```
2015-10-04 09:07:57:570 INFO  {db=Test} /127.0.0.1:63421 - Read 311 bytes:    ☺s   ♥sql  ☺%BEGIN
 LET activityVersionVertex = SELECT * FROM #21:137 WHERE #14:0 IN in_ActivityVersionAuthor.out[@rid]
 LET updatedActivityVersion = UPDATE $activityVersionVertex SET categoriesDelta = {"@type":"d","delta":[{"id":"44-22-1", "displayName":"Medium"}]}, modifiedDate = 1443974877568
```

COMMIT
   [OChannelBinaryServer]{db=Test} Error on unmarshalling content. Class: s java.lang.IllegalArgumentException: No enum constant com.orientechnologies.orient.core.command.OCommandDistributedReplicateRequest.DISTRIBUTED_EXECUTION_MODE.BEGIN
 LET activityVersionVertex = SELECT * FROM #21:137 WHERE #14:0 IN in_ActivityVersionAuthor.out[@rid]
 LET updatedActivityVersion = UPDATE $activityVersionVertex SET categoriesDelta = {"@type":"d","delta":[{"id":"44-22-1","displayName":"Medium"}]}, modifiedDate = 1443974877568

COMMIT
```
        at java.lang.Enum.valueOf(Unknown Source)
        at com.orientechnologies.orient.core.command.OCommandDistributedReplicateRequest$DISTRIBUTED_EXECUTION_MODE.valueOf(OCommandDistributedReplicateRequest.java:29)
        at com.orientechnologies.orient.core.command.script.OCommandScript.fromStream(OCommandScript.java:78)
        at com.orientechnologies.orient.core.serialization.serializer.stream.OStreamSerializerAnyStreamable.fromStream(OStreamSerializerAnyStreamable.java:77)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1285)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:396)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

```
Are the binary protocol versions different?

**Comment by lvca** [comment]
What's the command you execute?

**Comment by alpeshgaglani** [comment]
Here's my orientjs code:
        return db
           .let("activityVersionVertex", function (s) {
             return s.select().from(activityVersionRId)
                .where(userRId.toString() + " IN in_ActivityVersionAuthor.out[@rid]");
        })
            .let("updatedActivityVersion", function (s) {
            return s.update("$activityVersionVertex")
                .set({ categoriesDelta: { "@type": "d", delta: deltaObj}, modifiedDate: Date.now() });
        })
            .commit().all();

In this case, deltaObj is an object like so: [{"id":"44-22-1", "displayName":"Medium"}] 
This used to work just fine before the upgrade, and the corresponding upgrade command works from console/studio, but not from orientjs?

**Comment by alpeshgaglani** [comment]
Updated the title to reflect my latest findings: All multi-line transactions are failing with OrientJS 2.0.0 with OrientDB 2.1.3

**Comment by janjilek** [comment]
Same for me. After update to OrientDB 2.1.3 multi line transactions are not working. Update to Orientjs 2.1.0 doesn't fix the problem. 

Error response object:
{ [OrientDB.RequestError: No enum constant com.orientechnologies.orient.core.command.OCommandDistributedReplicateRequest.DISTRIBUTED_EXECUTION_MODE.BEGIN
 LET deliveryType = SELECT * FROM Type WHERE name = "game" LIMIT 1
 LET product = INSERT INTO Product SET uuid = "uuid"
 LET updatedProduct = UPDATE $product SET delivery = $deliveryType[0]
 
COMMIT RETRY 100 
 RETURN $product]
  name: 'OrientDB.RequestError',
  message: 'No enum constant com.orientechnologies.orient.core.command.OCommandDistributedReplicateRequest.DISTRIBUTED_EXECUTION_MODE.BEGIN\n LET deliveryType = SELECT * FROM Type WHERE name = "game" LIMIT 1\n LET product = INSERT INTO Product SET uuid = "uuid"\n LET updatedProduct = UPDATE $product SET delivery = $deliveryType[0]\n \nCOMMIT RETRY 100 \n RETURN $product',
  data: {},
  previous: 
   [ { [OrientDB.RequestError: Error on unmarshalling content. Class: s]
       name: 'OrientDB.RequestError',
       message: 'Error on unmarshalling content. Class: s',
       data: {},
       type: 'com.orientechnologies.orient.core.exception.OSerializationException' } ],
  id: 1,
  type: 'java.lang.IllegalArgumentException',
  hasMore: 1 }

Stacktrace:
Error on unmarshalling content. Class: s
java.lang.IllegalArgumentException: No enum constant com.orientechnologies.orient.core.command.OCommandDistributedReplicateRequest.DISTRIBUTED_EXECUTION_MODE.BEGIN
/* sql transaction code */
at java.lang.Enum.valueOf(Enum.java:238)
	at com.orientechnologies.orient.core.command.OCommandDistributedReplicateRequest$DISTRIBUTED_EXECUTION_MODE.valueOf(OCommandDistributedReplicateRequest.java:29)
	at com.orientechnologies.orient.core.command.script.OCommandScript.fromStream(OCommandScript.java:78)
	at com.orientechnologies.orient.core.serialization.serializer.stream.OStreamSerializerAnyStreamable.fromStream(OStreamSerializerAnyStreamable.java:77)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1285)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:396)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

**Comment by lvca** [comment]
Hi guys, I found the problem: starting from 2.1.3 you can decide where to execute a script when you run distributed (on target node or on all the nodes). Unfortunately this feature didn't change the binary protocol allowing a back-compatibility. I'm working on this.

**Comment by lvca** [comment]
Fixed on separate branch, please @maggiolo00 could you review it? In the meanwhile I'm fixing OrientDB server 2.1.4-SNAPSHOT to handle backward compatibility for this case.

**Comment by lvca** [comment]
Ok, OrientDB 2.1.4-SNAPSHOT should be compatible with current and past releases of OrientJS.

**Comment by lvca** [comment]
Removed branch #issue_102, because server can handle now this case.

**Comment by alpeshgaglani** [comment]
Thanks Luca. How I can get those bits?

**Comment by lvca** [comment]
We'll release 2.1.4 in the next days. In the meanwhile you can use last SNAPSHOT:

https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.1.4-SNAPSHOT/orientdb-community-2.1.4-20151005.182911-1-distribution.tar.gz

**Comment by alpeshgaglani** [comment]
Thanks a lot! It works great.

**Comment by lvca** [comment]
Thanks for reporting it.
