### ISSUE TITLE
crash when running in debug mode with babel

### ISSUE THREAD

**Issue by arisAlexis** [orientechnologies/orientjs#110]
I have a rather weird setup and I am unsure where to report this.I have already reported it to forever-agent too.

I am using orientjs driver that apparently has something to do with forever but don't know what exactly since it's just a module.

My program runs fine with just nodemon but if I try to debug with bode-debug (frontend for node-inspector and babel) I get this:

Debugger listening on port 5858
/home/aris/code/social/server/node_modules/orientjs/node_modules/request/node_modules/*forever-agent/index.js:97*
ForeverAgentSSL.prototype.addRequestNoreuse = AgentSSL.prototype.addRequest
^
TypeError: Cannot read property 'prototype' of undefined
at Object. (/home/aris/code/social/server/node_modules/orientjs/node_modules/request/node_modules/forever-agent/index.js:97:55)
at Module._compile (module.js:460:26)
at Module._extensions..js (module.js:478:10)
at Object.require.extensions.(anonymous function) as .js
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object. (/home/aris/code/social/server/node_modules/orientjs/node_modules/request/request.js:21:20)
at Module._compile (module.js:460:26)
at Module._extensions..js (module.js:478:10)
at Object.require.extensions.(anonymous function) as .js
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
at require (module.js:384:17)

**Comment by maggiolo00** [comment]
hi @arisAlexis how can replicate this?

how do you connect to your ODB instance?

**Comment by arisAlexis** [comment]
I will prepare a test case

**Comment by maggiolo00** [comment]
Thanks @arisAlexis

**Comment by arisAlexis** [comment]
im closing, it happens only when the breakpoint is hit in the first line but not if it doesn't , it's some kind of race condition but if i run node-inspector and then node --debug then everything runs ok.
