### ISSUE TITLE
Cannot route COMMAND operation to the distributed node (on distributed mode only)

### ISSUE THREAD

**Issue by rajeshvaya** [orientechnologies/orientjs#140]
# Version 
2.1.9 Community 

# Query 
Select count(*) form vertex_name

# NodeJS Driver function
db.query("Select count(*) form vertex_name");

# Stack trace
```
Cannot route COMMAND operation to the distributed node
java.lang.NullPointerException
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.mergeResultByAggregation(ODistributedStorage.java:439)
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.command(ODistributedStorage.java:306)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:72)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1323)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:400)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

# Description
We have only one OrientDB node currently running on distributed mode and all the queries are running fine as it should except the count(*), The same query returns proper result on the normal non-distributed mode.

When we run the count(*) query from the Studio for the distributed mode it runs fine, but not with the NodeJS driver (possible because of binary protocol for transport)

**Comment by mindnuts** [comment]
@maggiolo00 This seems like a serious issue. Why is it still not closed?

**Comment by maggiolo00** [comment]
@mindnuts 
let me check seems related to Distributed Part.

**Comment by maggiolo00** [comment]
@lvca 
Do you know if this is solved?

**Comment by lvca** [comment]
Yes, fixed long time ago
