### ISSUE TITLE
db.exec giving maximum call stack exceeded

### ISSUE THREAD

**Issue by bytebrahma** [orientechnologies/orientjs#162]
Hi,

 I am calling ``` db.exec(sql, params) ``` for the below query and handling the promise with then()
```
TRAVERSE both() from (SELECT * FROM fields  where  fieldname = :fieldname)  strategy DEPTH_FIRST
{ params: { fieldname: 'PIN_NUM' } }
 ```

and I got the below error. Could you please advise a workaround?
```
node.exe : D:\dev\temp\myexpress\node_modules\orientjs\lib\transport\binary\protocol28\operation.js:750
At line:1 char:5
+ node <<<<  app.js
    + CategoryInfo          : NotSpecified: (D:\dev\temp\mye...peration.js:750:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
          this.readOps.push.apply(this.readOps, remainingOps);
                            ^

RangeError: Maximum call stack size exceeded
    at null.<anonymous> (D:\dev\temp\myexpress\node_modules\orientjs\lib\transport\binary\protocol28\operation.js:750:29)
    at Operation.parseString (D:\dev\temp\myexpress\node_modules\orientjs\lib\transport\binary\protocol28\operation.js:671:12)
    at Operation.consume (D:\dev\temp\myexpress\node_modules\orientjs\lib\transport\binary\protocol28\operation.js:446:35)
    at Connection.process (D:\dev\temp\myexpress\node_modules\orientjs\lib\transport\binary\connection.js:383:17)
    at Connection.handleSocketData (D:\dev\temp\myexpress\node_modules\orientjs\lib\transport\binary\connection.js:284:17)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

```

**Comment by maggiolo00** [comment]
hi @bytebrahma 

how many records does the query return?

**Comment by bytebrahma** [comment]
1. count(*) with ```  bothE(), bothV() ```  returns __758259__ rows
2. count(*) with just ``` both() ``` returns __137267__ rows

Both the queries properly in orientdb studio but fail in my code (_may be coz we can restrict the fetch count?_).

Also the problem doesn't occur when I restrict the query to ```inE(), outV() ```

is there a way to set max rows fetched in orientjs?

**Comment by maggiolo00** [comment]
hi @bytebrahma 

i don't know the max limit. Let me check.

You could increment the stack size. But the final solution will be with streaming

You can follow this issue
https://github.com/orientechnologies/orientjs/issues/116

**Comment by maggiolo00** [comment]
hi @bytebrahma 

i'm closing this since is duplicate
Thanks
Enrico
