### ISSUE TITLE
Distributed support not working on new server join

### ISSUE THREAD

**Issue by fridaystreet** [orientechnologies/orientjs#191]
Hi,

This fix (#111) appeared to add support for distributed servers, but only seems to address it when the connection is created. When further configuration change update messages are received for servers being added to the cluster it causes an exception as per below. 

config is undefined

node_modules/orientjs/lib/transport/binary/index.js:91
 var servers = config.members.filter(function (m) {
                              ^

TypeError: Cannot read property 'filter' of undefined
    at bindServers (/home/paul/dev/ember2-frontend/sane/data/ec/server/node_modules/sails-orientdb/node_modules/orientjs/lib/transport/binary/index.js:91:31)
    at BinaryTransport.<anonymous> (/home/paul/dev/ember2-frontend/sane/data/ec/server/node_modules/sails-orientdb/node_modules/orientjs/lib/transport/binary/index.js:129:20)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Connection.process (/home/paul/dev/ember2-frontend/sane/data/ec/server/node_modules/sails-orientdb/node_modules/orientjs/lib/transport/binary/connection.js:384:12)
    at Connection.handleSocketData (/home/paul/dev/ember2-frontend/sane/data/ec/server/node_modules/sails-orientdb/node_modules/orientjs/lib/transport/binary/connection.js:289:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)

Tracing it back to the Operation.prototype.consume function (line 361) in protocol33/operation.js

The function doesn't seem to handle the message type 80 and sends through an empty dictionary. Well it would do, but there seems to be a bug in line 432 which is trying to return the obj.data key which doesn't exist.

429        offset += 5; // ignore the next integer
430        obj = {};
431       offset += this.parsePushedData(buffer, offset, obj, 'data');
432        return [Operation.PUSH_DATA, offset, obj.data];

Any ideas how to get this working?

Cheers
Paul

**Comment by maggiolo00** [comment]
Hi @fridaystreet  which version of OrientDB?

**Comment by fridaystreet** [comment]
Hi Enrico,

I've tried lots of versions, but for arguments sake let's say 2.2.2

Cheers
Paul

**Comment by maggiolo00** [comment]
hi @fridaystreet 

seems that the fix has not been ported well in 2.2.x version.
I will fix it for the next release.

Thanks

**Comment by fridaystreet** [comment]
No worries much appreciated

**Comment by maggiolo00** [comment]
hi @fridaystreet fixed in 2.2.2

thanks

**Comment by fridaystreet** [comment]
Awesome thanks
