### ISSUE TITLE
Enable token by default

### ISSUE THREAD

**Issue by maggiolo00** [orientechnologies/orientjs#213]

**Comment by Enteee** [comment]
when you do this, please also document how to handle the following error which emerges when you use the same connection for a long time.

```
{ OrientDB.RequestError: The token provided is expired
    at child.Operation.parseError (/some/path/you/dont/need/to/know/node_modules/orientjs/lib/transport/binary/p
rotocol33/operation.js:864:13)
    at child.Operation.consume (/some/path/you/dont/need/to/know/node_modules/orientjs/lib/transport/binary/prot
ocol33/operation.js:455:35)
    at Connection.process (/some/path/you/dont/need/to/know/node_modules/orientjs/lib/transport/binary/connectio
n.js:399:17)
    at Connection.handleSocketData (/some/path/you/dont/need/to/know/node_modules/orientjs/lib/transport/binary/
connection.js:290:20)                                                                                                  
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)                                                                                   
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)                                                               
    at TCP.onread (net.js:548:20)
  name: 'OrientDB.RequestError',                                                                                       
  message: 'The token provided is expired',
  data: {},                                                                                                            
  previous: [],
  id: 1,                                                                                                               
  type: 'com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException',                              
  hasMore: 0 }
```
