### ISSUE TITLE
[TypeError: Cannot read property 'operations' of null]

### ISSUE THREAD

**Issue by CTScognitives** [orientechnologies/orientjs#221]
hi,

I am using orientjs latest version in my nodejs app to connect with orientdb database. I have used the app in AWS where the database is present. It is running without any errors.But when i hosted my app in Azure, i am getting the following errors when connecting to the database in AWS. Any help would be appreciated.Thanks in Advance

`{ [OrientDB.ConnectionError [ECONNREFUSED]: connect ECONNREFUSED xxxxx:2424]
  name: 'OrientDB.ConnectionError [ECONNREFUSED]',
  code: 'ECONNREFUSED',
  message: 'connect ECONNREFUSED xxxxxx:2424',
  data: {} }`

> Unhandled rejection TypeError: Cannot read property 'operations' of null
    at D:\home\site\wwwroot\node_modules\orientjs\lib\transport\binary\connection.js:86:29
    at tryCatcher (D:\home\site\wwwroot\node_modules\orientjs\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._resolveFromResolver (D:\home\site\wwwroot\node_modules\orientjs\node_modules\bluebird\js\main\promise.js:476:31)
    at new Promise (D:\home\site\wwwroot\node_modules\orientjs\node_modules\bluebird\js\main\promise.js:69:37)
    at Connection._sendOp (D:\home\site\wwwroot\node_modules\orientjs\lib\transport\binary\connection.js:84:10)
    at Connection.send (D:\home\site\wwwroot\node_modules\orientjs\lib\transport\binary\connection.js:68:17)
    at D:\home\site\wwwroot\node_modules\orientjs\lib\transport\binary\index.js:291:38
    at tryCatcher (D:\home\site\wwwroot\node_modules\orientjs\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._resolveFromResolver (D:\home\site\wwwroot\node_modules\orientjs\node_modules\bluebird\js\main\promise.js:476:31)
    at new Promise (D:\home\site\wwwroot\node_modules\orientjs\node_modules\bluebird\js\main\promise.js:69:37)
    at BinaryTransport.send (D:\home\site\wwwroot\node_modules\orientjs\lib\transport\binary\index.js:289:12)
    at Server.send (D:\home\site\wwwroot\node_modules\orientjs\lib\server\index.js:113:25)
    at Db.close (D:\home\site\wwwroot\node_modules\orientjs\lib\db\db.js:132:22)
    at Db.<anonymous> (D:\home\site\wwwroot\db.js:117:12)
    at bound (domain.js:287:14)
    at Db.runBound (domain.js:300:12)

**Comment by maggiolo00** [comment]
hi @CTScognitives 

seems that the app cannot reach the database. Did you open the 2424 port
in the AWS server?

**Comment by CTScognitives** [comment]
Hi,

Thanks for the fast reply. I have opened another port 8080 in the AWS for the orientdb database. Will it do ?

**Comment by maggiolo00** [comment]
You should set also in your app 8080 port to orientjs config.

**Comment by CTScognitives** [comment]
I have mentioned that in my db settings file.It is working fine when i hosted the app in the same AWS.but it is failing only when i am trying to connect the db from another site and giving this error "Unhandled rejection TypeError: Cannot read property 'operations' of null" 

Should i start my db again with default 2424 port?

**Comment by maggiolo00** [comment]
this is the first error log when trying to connect to the db.

```
{ [OrientDB.ConnectionError [ECONNREFUSED]: connect ECONNREFUSED xxxxx:2424] name: 'OrientDB.ConnectionError [ECONNREFUSED]', code: 'ECONNREFUSED', message: 'connect ECONNREFUSED xxxxxx:2424', data: {} }
```
You can try to start the db with 2424

**Comment by maggiolo00** [comment]
@CTScognitives 

were you able to solve it?

**Comment by CTScognitives** [comment]
Hi,
I am trying to install orientdb into AWS but i am not able to start the server 
when i am using the "service orientdb start" it gives me this error
> /etc/init.d/orientdb: 22: [: 794: unexpected operator

and when i am using "./server.sh" it throws me the following error 

> SEVER Unable to listen for connections using the configured ports '2424-2430' on host '0.0.0.0' [OServerNetworkListener]

**Comment by CTScognitives** [comment]
Hey,
I have re-started the db with binary port as 2424 and http port as 8080.
Even though,i am still getting the error 

> { [OrientDB.ConnectionError [ECONNREFUSED]: connect ECONNREFUSED xxxxxx:8082]
  name: 'OrientDB.ConnectionError [ECONNREFUSED]',
  code: 'ECONNREFUSED',
  message: 'connect ECONNREFUSED xxxxx:8082',
  data: {} }

I previously set the binary port as 8082 and changed it to 2424 but it still doesnt change i think. Please tell me what i need to change so that it will be listen to 2424 port.

**Comment by maggiolo00** [comment]
@CTScognitives 

did you solve it?

**Comment by mastilver** [comment]
Hi

It looks like I have the same problem

Everything is working fine when I run my node server using node@6.9.3 on linux
But I get that error when running the node server (same version 6.9.3) inside a docker image

Here's how I run the container: 
```sh
docker run -d --name node-server -p 3000:3000 --link redis:redis-service --link orientdb:orientdb-service node-server
```

Then When I log: `docker logs node-server`, I got:
```
Unhandled rejection TypeError: Cannot read property 'operations' of null
    at /node_modules/orientjs/lib/transport/binary/connection.js:86:29
    at tryCatcher (/node_modules/orientjs/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/node_modules/orientjs/node_modules/bluebird/js/main/promise.js:476:31)
    at new Promise (/node_modules/orientjs/node_modules/bluebird/js/main/promise.js:69:37)
    at Connection._sendOp (/node_modules/orientjs/lib/transport/binary/connection.js:84:10)
    at Connection.send (/node_modules/orientjs/lib/transport/binary/connection.js:68:17)
    at BinaryTransport.<anonymous> (/node_modules/orientjs/lib/transport/binary/index.js:302:53)
    at BinaryTransport.tryCatcher (/node_modules/orientjs/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/node_modules/orientjs/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/node_modules/orientjs/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromiseAtPostResolution (/node_modules/orientjs/node_modules/bluebird/js/main/promise.js:244:10)
    at Async._drainQueue (/node_modules/orientjs/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/node_modules/orientjs/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/node_modules/orientjs/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
```

-----

Are you aware for any issue running the `orientjs` library inside a `node` container?

**Comment by mastilver** [comment]
It was an issue with my code: I was using the props: `hostname` rather than `host`...
It was defaulting to `localhost` which is fine on my laptop, not inside a docker container

**Comment by maggiolo00** [comment]
cool @mastilver 

@CTScognitives 

what about you? did you solve it?

can i close this issue?

Thanks

**Comment by maggiolo00** [comment]
@CTScognitives 

i'm closing this. Feel free to reopen it if you didn't solve it

Thanks

**Comment by CTScognitives** [comment]
@maggiolo00  Thanks for your time. We moved from this issue long ago
