### ISSUE TITLE
error in setting date or datetime properties when creating records

### ISSUE THREAD

**Issue by creisle** [orientechnologies/orientjs#240]
orientdb version: 2.2.17
orientjs version: 2.2.3
OS: centos06
node version: v6.10.0

I am getting an error when I try to create a record using "sysdate()" for a class with a datetime or date property

minimal reproducible script below

```
const OrientDB  = require('orientjs');

const serverConf = {
    host: 'localhost',
    HTTPport: 2480,
    username: 'root',
    password: 'root'
};
// set up the database server
const server = OrientDB(serverConf);

server.create({name: 'test', username: 'admin', password: 'admin'})
    .catch((error) => {
        return server.drop('test');
    }).then(() => {
        return server.use({name: 'test', username: 'admin', password: 'admin'});
    }).then((db) => {
        // make the first class
        db.class.create('test_class', 'V')
            .then((cls) => {
                // create a property
                cls.property.create({name: 'test_prop', type: 'datetime'})
                    .then(() => {
                        // properties have been created
                        // try to create a vertex
                        return cls.create({test_prop: db.rawExpression("sysdate()")});
                    }).then((record) => {
                        console.log('created record', record);
                    }).catch((error) => {
                        console.log(error);
                    });
            });
    }).catch((error) => {
        console.log(error);
    });

const cleanup = () => {
    server.drop({name: 'test'})
        .then(() => {
            return server.close();
        }).catch((error) => {
            console.log('error');
            return server.close();
        });
};

process.on('SIGINT', cleanup);
process.on('uncaughtException', cleanup);
```

what i get is the following error

```
{ OrientDB.RequestError: Error during saving of record with rid #25:-1
	DB name="test"
    at child.Operation.parseError (/home/creisle/git/knowledgebase/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:864:13)
    at child.Operation.consume (/home/creisle/git/knowledgebase/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:455:35)
    at Connection.process (/home/creisle/git/knowledgebase/node_modules/orientjs/lib/transport/binary/connection.js:399:17)
    at Connection.handleSocketData (/home/creisle/git/knowledgebase/node_modules/orientjs/lib/transport/binary/connection.js:290:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
  name: 'OrientDB.RequestError',
  message: 'Error during saving of record with rid #25:-1\r\n\tDB name="test"',
  data: {},
  previous: 
   [ { OrientDB.RequestError
         at child.<anonymous> (/home/creisle/git/knowledgebase/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:881:16)
         at child.Operation.parseByte (/home/creisle/git/knowledgebase/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:524:12)
         at child.Operation.consume (/home/creisle/git/knowledgebase/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:455:35)
         at Connection.process (/home/creisle/git/knowledgebase/node_modules/orientjs/lib/transport/binary/connection.js:399:17)
         at Connection.handleSocketData (/home/creisle/git/knowledgebase/node_modules/orientjs/lib/transport/binary/connection.js:290:20)
         at emitOne (events.js:96:13)
         at Socket.emit (events.js:188:7)
         at readableAddChunk (_stream_readable.js:176:18)
         at Socket.Readable.push (_stream_readable.js:134:10)
         at TCP.onread (net.js:548:20) name: 'OrientDB.RequestError', message: undefined, data: {} },
     { OrientDB.RequestError: null
         at child.<anonymous> (/home/creisle/git/knowledgebase/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:881:16)
         at child.Operation.parseByte (/home/creisle/git/knowledgebase/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:524:12)
         at child.Operation.consume (/home/creisle/git/knowledgebase/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:455:35)
         at Connection.process (/home/creisle/git/knowledgebase/node_modules/orientjs/lib/transport/binary/connection.js:399:17)
         at Connection.handleSocketData (/home/creisle/git/knowledgebase/node_modules/orientjs/lib/transport/binary/connection.js:290:20)
         at emitOne (events.js:96:13)
         at Socket.emit (events.js:188:7)
         at readableAddChunk (_stream_readable.js:176:18)
         at Socket.Readable.push (_stream_readable.js:134:10)
         at TCP.onread (net.js:548:20)
       name: 'OrientDB.RequestError',
       message: null,
       data: {},
       type: 'java.lang.ClassCastException',
       hasMore: 0,
       javaStackTrace: <Buffer ac ed 00 05 73 72 00 3e 63 6f 6d 2e 6f 72 69 65 6e 74 65 63 68 6e 6f 6c 6f 67 69 65 73 2e 6f 72 69 65 6e 74 2e 63 6f 72 65 2e 65 78 63 65 70 74 69 6f ... > } ],
  id: 1,
  type: 'com.orientechnologies.orient.core.exception.ODatabaseException',
  hasMore: 1 }
```

To test if this was an orientdb problem I tried to create the vertex using the GUI/console. That works fine 

```
create vertex test_class set test_prop=sysdate()
```

**Comment by maggiolo00** [comment]
hi @creisle 

`db.rawExpression()` works only if you use query builder to create records

You use this api to create the record that means that you should give a value eg `new Date()`
because the api serialize the input Object in a binary format and send it to the server.

http://orientdb.com/docs/last/OrientJS-Class-Records.html#creating-records

If you want to use the raw expression you should use the query builder

http://orientdb.com/docs/last/OrientJS-Query-Insert.html

**Comment by creisle** [comment]
ok great! that works. Thank you :)
