### ISSUE TITLE
Connect to remote server not working

### ISSUE THREAD

**Issue by RubenVermeulen** [orientechnologies/orientjs#258]
Hi

I've been trying to connect to a remote OrientDB database. Unfortunately I've not been able to make the connection. I'm using following code.

PS: I've tried the Java library and there the connection succeeds.

```
import orientdb from 'orientjs';

export default new orientdb.ODatabase({
  host: '69.69.69.69',
  port: 2424,
  username: 'admin',
  password: 'admin',
  name: 'GratefulDeadConcerts',
  useToken: true,
});
```
The error I get is the following:

```
Unhandled rejection OrientDB.RequestError
    at child.Operation.parseError (/home/ruben/Code/Uber Project/Server/WebSocket/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:864:13)
    at child.Operation.consume (/home/ruben/Code/Uber Project/Server/WebSocket/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:455:35)
    at Connection.process (/home/ruben/Code/Uber Project/Server/WebSocket/node_modules/orientjs/lib/transport/binary/connection.js:410:17)
    at Connection.handleSocketData (/home/ruben/Code/Uber Project/Server/WebSocket/node_modules/orientjs/lib/transport/binary/connection.js:301:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:559:20)
Unhandled rejection OrientDB.RequestError
    at child.Operation.parseError (/home/ruben/Code/Uber Project/Server/WebSocket/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:864:13)
    at child.Operation.consume (/home/ruben/Code/Uber Project/Server/WebSocket/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:455:35)
    at Connection.process (/home/ruben/Code/Uber Project/Server/WebSocket/node_modules/orientjs/lib/transport/binary/connection.js:410:17)
    at Connection.handleSocketData (/home/ruben/Code/Uber Project/Server/WebSocket/node_modules/orientjs/lib/transport/binary/connection.js:301:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:559:20)
Unhandled rejection OrientDB.RequestError
    at child.Operation.parseError (/home/ruben/Code/Uber Project/Server/WebSocket/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:864:13)
    at child.Operation.consume (/home/ruben/Code/Uber Project/Server/WebSocket/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:455:35)
    at Connection.process (/home/ruben/Code/Uber Project/Server/WebSocket/node_modules/orientjs/lib/transport/binary/connection.js:410:17)
    at Connection.handleSocketData (/home/ruben/Code/Uber Project/Server/WebSocket/node_modules/orientjs/lib/transport/binary/connection.js:301:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:559:20)
Unhandled rejection OrientDB.RequestError
    at child.Operation.parseError (/home/ruben/Code/Uber Project/Server/WebSocket/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:864:13)
    at child.Operation.consume (/home/ruben/Code/Uber Project/Server/WebSocket/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:455:35)
    at Connection.process (/home/ruben/Code/Uber Project/Server/WebSocket/node_modules/orientjs/lib/transport/binary/connection.js:410:17)
    at Connection.handleSocketData (/home/ruben/Code/Uber Project/Server/WebSocket/node_modules/orientjs/lib/transport/binary/connection.js:301:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:559:20)
Unhandled rejection OrientDB.RequestError
    at child.Operation.parseError (/home/ruben/Code/Uber Project/Server/WebSocket/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:864:13)
    at child.Operation.consume (/home/ruben/Code/Uber Project/Server/WebSocket/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:455:35)
    at Connection.process (/home/ruben/Code/Uber Project/Server/WebSocket/node_modules/orientjs/lib/transport/binary/connection.js:410:17)
    at Connection.handleSocketData (/home/ruben/Code/Uber Project/Server/WebSocket/node_modules/orientjs/lib/transport/binary/connection.js:301:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:559:20)
```

**Comment by maggiolo00** [comment]
Hi @RubenVermeulen 

which version of OrientJS and OrientDB?

**Comment by RubenVermeulen** [comment]
@maggiolo00 

OrientJS: 2.2.5
OrientDB: 2.2.20

**Comment by maggiolo00** [comment]
@RubenVermeulen 

which operation do you do with the Database?

Do you have a snippet to reproduce this issue?

**Comment by maggiolo00** [comment]
@RubenVermeulen 

it works fine for me with this

```
const ODatabase = require('orientjs').ODatabase;


var db = new ODatabase({
  host: '192.168.1.64',
  port: 2424,
  username: 'admin',
  password: 'admin',
  name: 'GratefulDeadConcerts',
  useToken: true
});

db.open().then(function () {
  var sql = "select from V limit 1";


  db.query(sql, {})
    .then(function (records) {
      console.log(records.length);

    });
});
```

**Comment by RubenVermeulen** [comment]
@maggiolo00 

I figured it out. I was trying to start live queries on types which didn't exists. Because my local version of the database contains more types than my online database I ran into the problem. A very confusing exception.

**Comment by maggiolo00** [comment]
hi @RubenVermeulen 

which was the live query you where doing?
You should get parsing error exception.

**Comment by RubenVermeulen** [comment]
@maggiolo00 

I was using the following.

```
db.liveQuery('LIVE SELECT FROM User').on('...')
```

The exception gave a parse error, but didn't stated where the exception occurred.
