### ISSUE TITLE
BUG on Connections?

### ISSUE THREAD

**Issue by tiagodavi** [orientechnologies/orientjs#272]
I've received this error when I tried to do a load test on my API using Orientjs. When I increase the number of clients orientjs dies!

0|bim-stag |     at createUnsafeBuffer (buffer.js:39:12)
0|bim-stag |     at allocate (buffer.js:182:12)
0|bim-stag |     at Function.Buffer.allocUnsafe (buffer.js:142:10)
0|bim-stag |     at new Buffer (buffer.js:79:19)

0|bim-stag |     at Connection.handleSocketData (node_m
odules/orientjs/lib/transport/binary/connection.js:281:14)
0|bim-stag |     at Connection.handleSocketData (node_m
odules/orientjs/lib/transport/binary/connection.js:300:12)

**Comment by tiagodavi** [comment]
RangeError: Maximum call stack size exceeded
    at Buffer.Uint8Array (native)
    at FastBuffer (buffer.js:12:5)
    at createUnsafeBuffer (buffer.js:39:12)
    at allocate (buffer.js:182:12)
    at Function.Buffer.allocUnsafe (buffer.js:142:10)
    at new Buffer (buffer.js:79:19)

**Comment by maggiolo00** [comment]
Hi @tiagodavi 

which is your orientjs configuration?

Do you have  a script to reproduce it?

**Comment by tiagodavi** [comment]
The same problem can be found here -> https://github.com/orientechnologies/orientjs/issues/116

I think this problem isn't related to the  "total records fetched" but this problem seems to be related to the "total buffer stored" into a variable in nodeJS.
