### ISSUE TITLE
"Maximum call stack size exceeded" trigerred by remote OrientDB exception

### ISSUE THREAD

**Issue by jbilcke** [orientechnologies/orientjs#273]
On OrientJS 2.2.6 + OrientDB 3.0 (which actually works fine with orientjs!)

 I got this infinite recursion error in the client, triggered by a server error :

```
On RangeError: Maximum call stack size exceeded
    at Buffer.Uint8Array (native)
    at FastBuffer (buffer.js:11:5)
    at allocate (buffer.js:184:13)
    at Function.Buffer.allocUnsafe (buffer.js:152:10)
    at new Buffer (buffer.js:83:19)
    at Connection.handleSocketData (node_modules/orientjs/lib/transport/binary/connection.js:292:14)
    at Connection.handleSocketData (node_modules/orientjs/lib/transport/binary/connection.js:311:12)
    at Connection.handleSocketData (node_modules/orientjs/lib/transport/binary/connection.js:311:12)
    at Connection.handleSocketData (node_modules/orientjs/lib/transport/binary/connection.js:311:12)
   ...
   ...
```

This was caused by an exception on the remote database side, which I fixed after going through the db server log (I was trying to run a query relying on a a vertex class that did not exist yet, causing an OCommandExecutionException) 

But still, it seems a bit dangerous to have such infinite recursion possible in the JS client, perhaps it could be improved?

**Comment by maggiolo00** [comment]
hi @jbilcke 

yes orientjs 2.2.6 works with OrientDB 3.0 since it will use the 2.2.x protocol.

this recursion probably is due to parsing error from the server. 

How can i reproduce this?

Are you able to reproduce this 2.2.x?

**Comment by maggiolo00** [comment]
Hi @jbilcke 

we just started shipping OrientJS 3.0 with the complete support of new OrientDB 3.0 features.
It's still in beta

here it's the [release](https://www.npmjs.com/package/orientjs/v/3.0.0-beta.0)

and there it's the [documentation](https://orientdb.com/docs/last/orientjs/OrientJS-beta.html)
