### ISSUE TITLE
Issue with migrations

### ISSUE THREAD

**Issue by nvtin** [orientechnologies/orientjs#278]
Hi guys.  I followed the ticket, also followed the answer of @kurtcorbett for this issue on another ticket which was closed at 2015 (https://github.com/orientechnologies/orientjs/issues/76). But today it happened to me even I did as he guided, can I reopen it here?
I am trying to make migrations with orientjs as in docs, steps at (https://github.com/orientechnologies/orientjs/issues/76) also but It didn't work.

**orientjs version is 2.2.6**
```
npm install orientjs -g
/usr/local/bin/orientjs -> /usr/local/lib/node_modules/orientjs/bin/orientjs
+ orientjs@2.2.6
updated 1 package in 4.634s
```
I created migrations folder, added orientjs.opts like this:
```
- server/
- node_modules/
- migrations/
- package.json
- orientjs.opts 
```
orientjs.opts file including:

```--host='localhost'
--port=2424
--user='root'
--password='xxxxxx'
--dbname='dev_data'
--dbuser='username'
--dbpassword='password_123@'
```
but when I try to run migrate command, it did not work.
```
$ orientjs db list          
Usage: orientjs [OPTIONS] [db|migrate]
Options:
  -d, --cwd         The working directory to use.       [default: "/Users/nvtin/workspace/ApideVN/chatbot/backend_src"]
  -h, --host        The server hostname or IP address.  [default: "localhost"]
  -p, --port        The server port.                    [default: 2424]
  -u, --user        The server username.                [default: "root"]
  -s, --password    The server password.              
  -n, --dbname      The name of the database to use.  
  -U, --dbuser      The database username.              [default: "admin"]
  -P, --dbpassword  The database password.              [default: "admin"]
  -?, --help        Show this help screen.         
```
```
$ orientjs db create test_db graph plocal
Usage: orientjs [OPTIONS] [db|migrate]

Options:
  -d, --cwd         The working directory to use.       [default: "/Users/nvtin/workspace/ApideVN/chatbot/backend_src"]
  -h, --host        The server hostname or IP address.  [default: "localhost"]
  -p, --port        The server port.                    [default: 2424]
  -u, --user        The server username.                [default: "root"]
  -s, --password    The server password.              
  -n, --dbname      The name of the database to use.  
  -U, --dbuser      The database username.              [default: "admin"]
  -P, --dbpassword  The database password.              [default: "admin"]
  -?, --help        Show this help screen.            
```

I have tried to add options on command line but I didn't also
```
$ orientjs -h="localhost" -p=2424 -u=root -s="xxxxxx" -U='username' -P='password_123@' db list 
Usage: orientjs [OPTIONS] [db|migrate]

Options:
  -d, --cwd         The working directory to use.       [default: "/Users/nvtin/workspace/ApideVN/chatbot/backend_src"]
  -h, --host        The server hostname or IP address.  [default: "localhost"]
  -p, --port        The server port.                    [default: 2424]
  -u, --user        The server username.                [default: "root"]
  -s, --password    The server password.              
  -n, --dbname      The name of the database to use.  
  -U, --dbuser      The database username.              [default: "admin"]
  -P, --dbpassword  The database password.              [default: "admin"]
  -?, --help        Show this help screen.            

/usr/local/lib/node_modules/orientjs/node_modules/bluebird/js/main/promise.js:673
            throw e;
            ^

Error: Cannot find module '/usr/local/lib/node_modules/orientjs/lib/cli/commands/Power'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at CLI.createCommand (/usr/local/lib/node_modules/orientjs/lib/cli/index.js:62:38)
    at CLI.<anonymous> (/usr/local/lib/node_modules/orientjs/lib/cli/index.js:33:20)
    at CLI.tryCatcher (/usr/local/lib/node_modules/orientjs/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/orientjs/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/orientjs/node_modules/bluebird/js/main/promise.js:577:18)
    at Async._drainQueue (/usr/local/lib/node_modules/orientjs/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/usr/local/lib/node_modules/orientjs/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/orientjs/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```
I am not sure what I am doing wrong or there is a bug. Can you guys help me or give me some solution on it? Thank you so much.

**Comment by nvtin** [comment]
I am sorry. It come from my side. I have found the issue I am getting. The password I used have blank string, so it didn't work. I tried to change my password and it worked.
So I will close this issue. Thanks.
