### ISSUE TITLE
OrientDB throws error when I use new range syntax in the projection on OrientDB v3.0.1

### ISSUE THREAD

**Issue by mehdizarepour** [orientechnologies/orientjs#313]
## Expected/Actual behavior  

When I use square brackets in the projection to get a range of items (like `[x..y]`), OrientDB throws an error, while when I run the same query using OrientDB Studio it works fine.

My query using OrientJS:
```js
db.select('expand(out("Friends")[0..2])')
  .from('User')
  .where({ id: 1 })
  .one();
```

Error:
```
Unhandled rejection OrientDB.RequestError: Error on parsing query
Query: 0..1
------^
        DB name="Test"
    at child.Operation.parseError (/home/test/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:905:13)
    at child.Operation.consume (/home/test/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:496:35)
    at Connection.process (/home/test/node_modules/orientjs/lib/transport/binary/connection.js:430:17)
    at Connection.handleSocketData (/home/test/node_modules/orientjs/lib/transport/binary/connection.js:314:20)

    at Socket.emit (events.js:180:13)

    at addChunk (_stream_readable.js:274:12)

    at readableAddChunk (_stream_readable.js:261:11)

    at Socket.Readable.push (_stream_readable.js:218:10)

    at TCP.onread (net.js:581:20)

```

## Steps to reproduce  

```sql
/* Schema */

create class User extends V;
create property User.id Integer;
create property User.name String;

CREATE CLASS Friends EXTENDS E;

insert into User set id = 1, name = "A";
insert into User set id = 2, name = "B";
insert into User set id = 3, name = "C";
insert into User set id = 4, name = "D";

CREATE EDGE Friends FROM (SELECT FROM User WHERE id = 1) to (SELECT FROM User WHERE id IN [2, 3, 4]);


/* Query */
db.select('expand(out("Friends")[0..2])')
  .from('User')
  .where({ id: 1 })
  .one();
```

**Comment by saeedtabrizi** [comment]
Hi @mehdizarepour 
I guess this issue occurred when use wrong or incompatible binary protocol in orientjs  to connect  ODB v3.0. 
Did  you try with `db.query` command ?

**Comment by mehdizarepour** [comment]
Hi @saeedtabrizi 
Yes, I did. the `db.query` command throws the same error.

**Comment by maggiolo00** [comment]
Hi @mehdizarepour, @saeedtabrizi 

orientjs still use the protocol version 33, that is not using the new SQL engine and syntax.

A new version of orientjs with the new protocol support will probably be shipped the next month.

Thanks
Enrico

**Comment by maggiolo00** [comment]
Hi @mehdizarepour 

we shipped the first version of the new OrientJS driver 3.0 with the complete support of OrientDB 3.0 features . 
It's in beta now 
https://www.npmjs.com/package/orientjs/v/3.0.0-beta.0

Documentation is here

https://orientdb.com/docs/last/orientjs/OrientJS-beta.html
