### ISSUE TITLE
Error: pool is draining and cannot accept work

### ISSUE THREAD

**Issue by petervavro** [orientechnologies/orientjs#342]
### I am trying :

```
const OrientDBClient = require('orientjs').OrientDBClient

  OrientDBClient.connect({
    host: config.get('orientdb.ip'),
    port: config.get('orientdb.port')
  }).then(client => {

    client.session({
      name: config.get('orientdb.db.name'),
      username: config.get('orientdb.username'),
      password: config.get('orientdb.password')
    })
      .then((session) => {

        session.query('select * from TestTable')
          .on('data', data => {

            console.log(data)

          })
          .on('error', (err) => {

            console.log(err)

          })
          .on('end', () => {

            console.log('End of the stream')

          })

        return session.close()

      })

    return client.close()

  }).then(() => {

    console.log('Client closed')

  })
```

### I am getting :

`Client closed
Error: pool is draining and cannot accept work
    at Pool.acquire (/node_modules/generic-pool/lib/Pool.js:434:9)
    at Promise (/node_modules/orientjs/lib/client/pool/index.js:36:10)
From previous event:
    at ONetworkPool.acquire (/node_modules/orientjs/lib/client/pool/index.js:34:12)
    at ONetworkBinary.acquireConnection (/node_modules/orientjs/lib/client/network/binary.js:31:22)
    at OServer.acquireForSubscribe (/node_modules/orientjs/lib/client/topology/server.js:61:29)
    at OServer.subscribeCluster (/node_modules/orientjs/lib/client/topology/server.js:68:19)
    at SessionManager.connection.send.bind.then (/node_modules/orientjs/lib/client/database/session.js:51:27)
From previous event:
    at opening.client.cluster.acquireFrom.then (/node_modules/orientjs/lib/client/database/session.js:44:12)
From previous event:
    at SessionManager.open (/node_modules/orientjs/lib/client/database/session.js:32:8)
    at ODatabaseSession.open (/node_modules/orientjs/lib/client/database/database.js:314:32)
    at OrientDBClient.session (/node_modules/orientjs/lib/client/client.js:82:15)
    at OrientDBClient.connect.then.client (/server/service/services.js:202:12)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Object.getServices (/server/service/services.js:200:6)
    at Object.getServices (/server/service/controller.js:51:32)
    at getServices (/server/service/handlers.js:57:31)
    at module.exports.internals.Manager.execute (/node_modules/hapi/lib/toolkit.js:35:106)
    at Object.internals.handler (/node_modules/hapi/lib/handler.js:52:48)
    at exports.execute (/node_modules/hapi/lib/handler.js:37:36)
    at module.exports.internals.Request._lifecycle (/node_modules/hapi/lib/request.js:261:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Waiting for the debugger to disconnect...
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

OrientDB version : 3.0.10
OrientJs version : 3.0.0-beta.1

**Comment by petervavro** [comment]
Node version : v10.11.0

**Comment by wolf4ood** [comment]
@petervavro 
you are closing the client before the query is fired.
By closing the client all the pools are closed. You should do something like this,
that close the session and then the client after the query is finished
```js
const OrientDBClient = require('orientjs').OrientDBClient

   OrientDBClient.connect({
    host: config.get('orientdb.ip'),
    port: config.get('orientdb.port')
  }).then(client => {

    client.session({
      name: config.get('orientdb.db.name'),
      username: config.get('orientdb.username'),
      password: config.get('orientdb.password')
    })
      .then((session) => {
        session.query('select * from TestTable')
          .on('data', data => {
            console.log(data)
          })
          .on('error', (err) => {
            console.log(err)
          })
          .on('end', () => {
            console.log('End of the stream');
            session.close().then(()=>{
              return client.close()
            }).then(()=>{
                console.log('Client closed')
            });
          })

      })

  })

```

**Comment by petervavro** [comment]
Thank you so much. This works well. 

I would like to ask one more favor. I guess, that will be useful for more people here (at least for me 👍 ). Could you please rewrite this to "async/await" version ?

Thank you. 

If is possible I really appreciate that !

**Comment by wolf4ood** [comment]
Hi @petervavro 
yes i will put example also with async/await

Thanks

**Comment by wolf4ood** [comment]
Hi @petervavro 

i've added an example example with  async/await.
https://github.com/orientechnologies/orientjs-example

Let me know if it helps

Thanks
