### ISSUE TITLE
INSERT INTO with CONTENT synax error when using params v3.0

### ISSUE THREAD

**Issue by myflowpl** [orientechnologies/orientjs#346]
OrientDB 3.0.10
OrientJS 3.0.1

this works:
````typescript
session.command('INSERT INTO Log CONTENT {test: "inline json"}')
````
and this:
```typescript
session.command( 'INSERT INTO Log CONTENT :log',  {
    params: {log: { test: 'json in params' }}
})
```

generates error:
````
OrientDB.RequestError: Error parsing query:
      INSERT INTO Log CONTENT ":log"
                            ^
      Encountered " <CONTENT> "CONTENT "" at line 1, column 17.
      Was expecting one of:
          <EOF> 
          <SELECT> ...
          <FROM> ...
          <RETURN> ...
          <UNSAFE> ...
          "(" ...
          ";" ...
          <CLUSTER> ...
          "(" ...
          
      	DB name="smdb_dev"
      	Error Code="1"
      at child.Object.<anonymous>.Operation.parseError (node_modules/orientjs/lib/client/network/protocol37/operation.js:1224:13)
      at child.Object.<anonymous>.Operation.consume (node_modules/orientjs/lib/client/network/protocol37/operation.js:566:35)
      at ONetworkConnection.Object.<anonymous>.Connection.process (node_modules/orientjs/lib/client/network/conn.js:460:17)
      at ONetworkConnection.Object.<anonymous>.Connection.handleSocketData (node_modules/orientjs/lib/client/network/conn.js:342:20)

````

It was working on 2.2 version
any ideas what i'm doing wrong ?

**Comment by wolf4ood** [comment]
Hi @myflowpl 

let me check

**Comment by wolf4ood** [comment]
Hi @myflowpl 

seems a limitation of the new parser shipped in 3.0.x.
I've got the same exception with Java Driver

**Comment by myflowpl** [comment]
@wolf4ood thanks for quick response!

I wish to migrate to 3.0 but this limitation is really holding me back

do you know any work around or other easy method to insert records witch are big json structure ?

should we re post this issue on orientdb ? 
or may be there are any other related issues already

**Comment by wolf4ood** [comment]
Hi @myflowpl 

i've tested the fix [here](https://github.com/orientechnologies/orientdb/issues/8666) also in orientjs and works fine

Thanks
