### ISSUE TITLE
Create Index Error: Cannot execute query on non idempotent statement

### ISSUE THREAD

**Issue by creisle** [orientechnologies/orientjs#356]
orientdb version: 3.0.6
orientjs version: 3.0.2

I run into the following error when I try to create an index 

```text
Unhandled rejection OrientDB.RequestError: Cannot execute query on non idempotent statement: CREATE INDEX ActiveUserGroupName ON UserGroup (name, deletedAt) unique METADATA {"ignoreNullValues":false}
	DB name="test_8705e4c9-9296-4907-ad6f-0b685c11a208"
    at child.Operation.parseError (.../node_modules/orientjs/lib/client/network/protocol37/operation.js:1224:13)
    at child.Operation.consume (.../node_modules/orientjs/lib/client/network/protocol37/operation.js:566:35)
    at ONetworkConnection.Connection.process (.../node_modules/orientjs/lib/client/network/conn.js:460:17)
    at ONetworkConnection.Connection.handleSocketData (.../node_modules/orientjs/lib/client/network/conn.js:342:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
```

**Comment by wolf4ood** [comment]
Hi @creisle 

how do you create the index?

**Comment by creisle** [comment]
Hi @wolf4ood,

Sorry about that, I have now extracted the code to a minimal reproducible version 
```js
const server = await OrientDBClient.connect({
    host: conf.server.host,
    port: conf.server.port
});
try {
    await server.createDatabase({
        name: 'test_index_bug',
        username: conf.server.user,
        password: conf.server.pass
    });
    const db = await server.session({
        name: 'test_index_bug',
        username: conf.db.user,
        password: conf.db.pass
    });
    const cls = await db.class.create('ExampleClass', 'V');
    await Promise.all([
        cls.property.create({type: 'string', name: 'prop1'}),
        cls.property.create({type: 'string', name: 'prop2'})
    ]);
    // create the index
    await db.index.create({
        name: 'ExampleIndex',
        type: 'unique',
        metadata: {ignoreNullValues: false},
        properties: ['prop1', 'prop2'],
        class: 'ExampleClass'
    });
} finally {
    // teardown
    await server.dropDatabase({
        name: 'test_index_bug',
        username: conf.server.user,
        password: conf.server.pass
    });
}
```

as far as I can tell it just seems to happen on creating any index using db.index.create?

**Comment by wolf4ood** [comment]
Hi @creisle 

thanks for the reproducer. I've pushed a fix. It will be available in the next OrientJS release

**Comment by wolf4ood** [comment]
Hi @creisle 

we have just release OrientJS 3.0.3 with the fix.
Thanks
