### ISSUE TITLE
Error: Resource not currently part of this pool

### ISSUE THREAD

**Issue by petervavro** [orientechnologies/orientjs#369]
I am randomly getting following error :
```
Error: Resource not currently part of this pool
    at Pool.release (/node_modules/generic-pool/lib/Pool.js:505:9)
    at ODatabaseSessionPool.release (/node_modules/hapi-orientdb/node_modules/orientjs/lib/client/pool/index.js:63:22)
    at ODatabaseSession.close (/node_modules/hapi-orientdb/node_modules/orientjs/lib/client/database/database.js:347:24)
    at Object.listener (/node_modules/hapi-orientdb/index.js:75:56)
    at module.exports.internals.Podium.internals.Podium.emit (/node_modules/podium/lib/index.js:228:107)
    at IncomingMessage.internals.event (/node_modules/hapi/lib/request.js:607:25)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at abortIncoming (_http_server.js:439:9)
    at socketOnEnd (_http_server.js:455:5)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
Waiting for the debugger to disconnect...
```
Restart of the server is required in order to get it to work again.

There are 0 sessions open at that moment. I using [hapi-orientdb](https://github.com/petervavro/hapi-orientdb).

What is wrong, please ?

**Comment by wolf4ood** [comment]
Hi @petervavro 

do you have a script to reproduce this?

Thanks
