### ISSUE TITLE
Unsupported Protocol : 36

### ISSUE THREAD

**Issue by creisle** [orientechnologies/orientjs#370]
orientdb: v2.2.37
orientjs: v3.0.5
nodejs: 8.11.2
OS: centos07

I would like to use some of the newer features in orientjs 3.X.X but I am unable to upgrade to orientdb v3 currently.

It is not clear to me from the documentation what the requirements are. v3.X.X says the api's are backwards compatible which would have lead me to assume that I should be able to use 3.X.X with orientdb 2.X.X? Is that correct?

I tried to change my connection over to using the new api

```js
 // set up the database server
const client = await OrientDBClient.connect({...});
const pool = await client.sessions({...});
```

But I get a protocol error

```
OrientDB.ProtocolError: Unsupported Protocol : 36
    at ONetworkConnection.bindProtocol (/.../node_modules/orientjs/lib/client/network/connection.js:29:13)
    at ONetworkConnection.<anonymous> (.../node_modules/orientjs/lib/client/network/conn.js:236:18)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
```

Am I doing something incorrect?

**Comment by wolf4ood** [comment]
Hi @creisle 

unfortunately those new apis works only with OrientDB 3.0.x.

You can still use OrientJS 3.. with OrientDB 2.2.x but you need to use the legacy API

https://orientdb.com/docs/3.0.x/orientjs/OrientJS-Legacy.html

Let me know if this helps

Thank
