### ISSUE TITLE
logger error with 3.0.8

### ISSUE THREAD

**Issue by grimace** [orientechnologies/orientjs#414]
I've been running 3.0.7 with no issues.  When I install 3.0.8 I get this:
```  at OServer.connect (<#user_path>gdb-admin/node_modules/orientjs/lib/client/topology/server.js:34:19)
    at Promise.all.servers.map.server (<#user_path>gdb-admin/node_modules/orientjs/lib/client/topology/cluster.js:99:25)
    at Array.map (<anonymous>)
    at Promise (<#user_path>gdb-admin/node_modules/orientjs/lib/client/topology/cluster.js:98:22)
    at Promise._execute (<#user_path>gdb-admin/node_modules/orientjs/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (<#user_path>gdb-admin/node_modules/orientjs/node_modules/bluebird/js/release/promise.js:488:18)
    at new Promise (<#user_path>gdb-admin/node_modules/orientjs/node_modules/bluebird/js/release/promise.js:79:10)
    at OCluster.connect (<#user_path>gdb-admin/node_modules/orientjs/lib/client/topology/cluster.js:96:12)
    at OrientDBClient.connect (<#user_path>gdb-admin/node_modules/orientjs/lib/client/client.js:46:10)
    at Object.<anonymous> (<#user_path>gdb-admin/app.js:467:6)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
```

same code for both versions

**Comment by wolf4ood** [comment]
Hi @grimace 

strange. Do you have this at startup of your app?

Thanks

**Comment by grimace** [comment]
I'm fairly sure it was at startup.  but I backed off to 3.0.7 and so am not seeing the error.

**Comment by wolf4ood** [comment]
@grimace 

strange i'm not able to see the root cause of this and i'm not able to reproduce this.

Do you have some tips to reproduce this?

Thanks

**Comment by grimace** [comment]
I have a running app.js ( with 3.07 ) and I switch to 3.08 and run npm install.

my code looks something like this, tho there is a bit more to it:

```
const client = new OrientDBClient({
  host: dbhost,
  db: "test",
  user: "test",
  password: "testpw",
  rootUser: "root",
  rootPassword: "rootpw",
  pool: {
    max: 1
  },
  logger: { warning: console.log.bind(null,"OrientDB: ") }
});

...

//---> happens here
client
    .connect()
    .then(() => {
      return client.sessions({
		  host: dbhost,
		  db: "test",
		  user: "test",
		  password: "testpw",
		  rootUser: "root",
		  rootPassword: "rootpw",
	      pool: {
			  max: 200
		  },
        logger: { warning: console.log.bind(null,"OrientDB: ") }
      });
  })
  .then(pool => {
    console.log('loading bootstrap pool ...')
    bootstrap(pool);
  })
  .catch(err => {
    console.log(err);
  });

log error happens like this:

[[05:50:48.371]] [LOG]    TypeError: this.logger.debug is not a function
    at OServer.connect (/Users/xxxxxxxx/projects/dbtest/node_modules/orientjs/lib/client/topology/server.js:34:19)
    at Promise.all.servers.map.server (/Users/xxxxxxxx/projects/dbtest/node_modules/orientjs/lib/client/topology/cluster.js:99:25)
    at Array.map (<anonymous>)
    at Promise (/Users/xxxxxxxx/projects/dbtest/node_modules/orientjs/lib/client/topology/cluster.js:98:22)
    at Promise._execute (/Users/xxxxxxxx/projects/dbtest/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/Users/xxxxxxxx/projects/dbtest/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/xxxxxxxx/projects/dbtest/node_modules/bluebird/js/release/promise.js:79:10)
    at OCluster.connect (/Users/xxxxxxxx/projects/dbtest/node_modules/orientjs/lib/client/topology/cluster.js:96:12)
    at OrientDBClient.connect (/Users/xxxxxxxx/projects/dbtest/node_modules/orientjs/lib/client/client.js:46:10)
    at Object.<anonymous> (/Users/xxxxxxxx/projects/dbtest/app.js:2350:6)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11

```

It's pretty weird IMHO.  maybe to do with pooling? I'm happy to try any suggestions.

**Comment by grimace** [comment]
this happens with every version after 3.0.07.  Any ideas?
it works if I comment out every reference to this.logger in the project.

**Comment by grimace** [comment]
it works if I comment out every reference to this.logger in the project.
