### ISSUE TITLE
Error on conversion of date '2020-03-17T07:54:15.214Z' using the format: yyyy-MM-dd HH:mm:ss

### ISSUE THREAD

**Issue by Nilesh-Kale-2212** [orientechnologies/orientjs#430]
I am using the Orient DB 3.0.29 and DB has the following configuration
![image](https://user-images.githubusercontent.com/51450361/78767368-21fe4500-79a8-11ea-8494-8cd928a46c92.png)

While getting the record from the database, the database throws an error.

````
OrientDB.RequestError: Error on conversion of date '2020-03-17T07:54:15.214Z' using the format: yyyy-MM-dd HH:mm:ss\r\n\tDB name=\"InteliNotionDB3\"\n    at child.Operation.parseError (/usr/src/app/node_modules/orientjs/lib/client/network/protocol37/operation.js:1247:13)\n    at child.Operation.consume (/usr/src/app/node_modules/orientjs/lib/client/network/protocol37/operation.js:571:35)\n    at ONetworkConnection.Connection.process (/usr/src/app/node_modules/orientjs/lib/client/network/conn.js:462:17)\n    at ONetworkConnection.Connection.handleSocketData (/usr/src/app/node_modules/orientjs/lib/client/network/conn.js:344:20)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)\n    at TCP.onread (net.js:639:20)
````
Where as the returning objects date property are stored within given format like "2020-04-08 03:40:24"

**Comment by Nilesh-Kale-2212** [comment]
I am closing this issue as we are not able to give the property reason/query of how the issue gets occurs.
