### ISSUE TITLE
Unable to establish a connection from Raspbian

### ISSUE THREAD

**Issue by odubuc** [orientechnologies/orientjs#57]
Here is my problem posted on stackoverflow:
http://stackoverflow.com/questions/31661273/unable-to-make-query-to-orientdb-using-orientjs

I tested on two distinct setup. One is running Windows 10 and the other one is runing Raspbian on a RaspberryPi 2. On both machine I have Node with Orientjs and OrientDB.

From Raspbian I am unable to establish a connection to OrientDB to localhost or the windows PC. 
From windows both DB works fine (localhost and remotely to the PI).

When I'm on Raspbian both DB give the same error.
Unhandled rejection OrientDB.ConnectionError [1]: Remote server closed the connection.
    at Connection.handleSocketEnd (/usr/share/adafruit/webide/repositories/my-pi-projects/Thermostat/node_modules/orientjs/lib/transport/binary/connection.js:320:9)
    at Socket.emit (events.js:104:17)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

Version information:
Raspbian: OriendDB(v2.0.13) using Orientjs(v2.0.0) on NodeJS(v0.12.2)
Windows: OriendDB(v2.0.13) using Orientjs(v2.0.0) on NodeJS(v0.12.5)

**Comment by odubuc** [comment]
I found out that another library I am using is causing the issue. I removed it and now everything works fine.
