### ISSUE TITLE
corrupted.

### ISSUE THREAD

**Issue by phpnode** [orientechnologies/orientjs#9]
_From @martingg88 on May 19, 2015 10:34_

any idea for following issue?
```
OrientDB.ProtocolError: Unknown Error on operation id REQUEST_COMMAND at Connection.process (C:\project\ctx\lib\node_modules\sails-orientdb\node_modules\oriento\lib\transport\binary\connection.js:384:15) at Connection.handleSocketData (C:\project\ctx\lib\node_modules\sails-orientdb\node_modules\oriento\lib\transport\binary\connection.js:279:17) at Socket.emit (events.js:107:17) at readableAddChunk (_stream_readable.js:163:16) at Socket.Readable.push (_stream_readable.js:126:10) at TCP.onread (net.js:529:20) From previous event: at Connection._sendOp (C:\project\ctx\lib\node_modules\sails-orientdb\node_modules\oriento\lib\transport\binary\connection.js:79:10) at Connection.send (C:\project\ctx\lib\node_modules\sails-orientdb\node_modules\oriento\lib\transport\binary\connection.js:63:17) at C:\project\ctx\lib\node_modules\sails-orientdb\node_modules\oriento\lib\transport\binary\connection-pool.js:65:23 From previous event: at ConnectionPool.send (C:\project\ctx\lib\node_modules\sails-orientdb\node_modules\oriento\lib\transport\binary\connection-pool.js:64:4) at BinaryTransport.send (C:\project\ctx\lib\node_modules\sails-orientdb\node_modules\oriento\lib\transport\binary\index.js:191:43) at Server.send (C:\project\ctx\lib\node_modules\sails-orientdb\node_modules\oriento\lib\server\index.js:112:25) at Db.<anonymous> (C:\project\ctx\lib\node_modules\sails-orientdb\node_modules\oriento\lib\db\index.js:152:24) at bound (domain.js:254:14) at Promise.runBound (domain.js:267:12) From previous event: at Db.send (C:\project\ctx\lib\node_modules\sails-orientdb\node_modules\oriento\lib\db\index.js:144:4) at Db.exec (C:\project\ctx\lib\node_modules\sails-orientdb\node_modules\oriento\lib\db\index.js:256:22) at Db.query (C:\project\ctx\lib\node_modules\sails-orientdb\node_modules\oriento\lib\db\index.js:288:15) at module.exports.Statement.extend.exec (C:\project\ctx\lib\node_modules\sails-orientdb\node_modules\oriento\lib\db\query.js:108:20) at module.exports.Statement.extend.one (C:\project\ctx\lib\node_modules\sails-orientdb\node_modules\oriento\lib\db\query.js:57:17) at C:\project\app\stream\api\services\oriento.js:374:26 at module.exports.dbHelper.getDB (C:\project\ctx\lib\node_modules\sails-orientdb\lib\connection.js:263:15) at bound.module.exports.adapter.getDB (C:\project\ctx\lib\node_modules\sails-orientdb\lib\adapter.js:195:44) at bound.self.(anonymous function) (C:\project\ctx\lib\node_modules\sails\node_modules\waterline\lib\waterline\query\adapters.js:35:29) at bound (C:\project\ctx\lib\node_modules\sails\node_modules\lodash\dist\lodash.js:729:21) at async.waterfall.action (C:\project\app\stream\api\services\oriento.js:368:23) at fn (C:\project\ctx\lib\node_modules\sails\node_modules\async\lib\async.js:641:34) at Immediate._onImmediate (C:\project\ctx\lib\node_modules\sails\node_modules\async\lib\async.js:557:34) at processImmediate [as _immediateCallback] (timers.js:358:17)
```

_Copied from original issue: codemix/oriento#313_

**Comment by phpnode** [comment]
@martingg88 what version of orientdb?

**Comment by phpnode** [comment]
_From @martingg88 on May 19, 2015 11:6_

it's for development version.

do you have any idea what cause this issue?

**Comment by phpnode** [comment]
@martingg88 which version of orientdb are you using?

**Comment by phpnode** [comment]
_From @martingg88 on May 19, 2015 11:9_

it should be VERSION 2.1-rc2. but i downloaded this from development branch.

**Comment by phpnode** [comment]
@martingg88 can you replicate this in a stable version of OrientDB?

**Comment by phpnode** [comment]
_From @martingg88 on May 19, 2015 11:15_

ok. i will try and let you know.

**Comment by phpnode** [comment]
_From @martingg88 on May 19, 2015 11:56_

double confirm with you that this issue happen for  VERSION 2.1-rc2 at master branch.

**Comment by phpnode** [comment]
@martingg88 what command are you sending?

**Comment by phpnode** [comment]
_From @martingg88 on May 19, 2015 14:49_

create edge command. But i run this command multiple time in parallel by using node.js asyn library.

**Comment by phpnode** [comment]
@martingg88 without more detail it's very hard to debug. Please could you create a minimal test file that replicates the issue? Just copy one of the existing files in `/test/bugs`

**Comment by phpnode** [comment]
_From @martingg88 on May 20, 2015 1:27_

sure. i will do it and let you know.
