### ISSUE TITLE
Server user not authenticated (OrientDB v2.0.15, OrientJS v2.0.0)

### ISSUE THREAD

**Issue by ledgr** [orientechnologies/orientjs#95]
Sent run-time exception to the client /127.0.0.1:39102: com.orientechnologies.orient.core.exception.OSecurityAccessException: Server user not authenticated.
com.orientechnologies.orient.core.exception.OSecurityAccessException: Server user not authenticated.
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.checkServerAccess(ONetworkProtocolBinary.java:469)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.listDatabases(ONetworkProtocolBinary.java:2140)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:283)
    at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
    at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

``````
var OrientDB = require('orientjs');

var server = OrientDB({
  host: "localhost",
  port: "2424",
  username: "root",
  password: "XXXXXXXXXXXXXXXXXXXXXX"
})
console.log('Connected to OrientDB server: ' +
    server.transport.username + '@' +
    server.transport.connection.host + ':' + server.transport.connection.port
);

var db = server.use({
  name: "database",
  username: "admin",
  password: "admin"
})

server.list()
.then(function (dbs) {
  console.log('There are ' + dbs.length + ' databases on the server.');
});

console.log('Using OrientDB database: ' + db.name);
orientdb.close();```
``````

**Comment by ledgr** [comment]
Same applies for OrientDB v2.1.0, OrientJS v2.0.0

**Comment by ledgr** [comment]
Same applies for OrientDB v2.1.2, OrientJS v2.0.0

**Comment by ledgr** [comment]
Pyorient is working fine.

**Comment by ledgr** [comment]
This even applies for OrientJS 2.2.0

**Comment by StarpTech** [comment]
@ledgr  Try to create a new user with `write` access in your db.

**Comment by ledgr** [comment]
I don't think this is database oriented error. That's more of a server auth error (e.g. "root"), because it says "Server user not authenticated", not "Database user". My script can't authenticate to server while using same credentials in orientdb console or studio I have no issues.
Anyway I have experimented creating new users - same issue. (OrientDB 2.1.2, OrientJS 2.0.0)

NodeJS script side log:
```
server: localhost:2424
server_username: root
server_password: XXXXXXXXXXXXXXXXX

database: new_database
db_username: writer
db_password: XXXXXXXXXXXXXXXXX

Using OrientDB database: new_database

{ [OrientDB.ConnectionError [2]: read ECONNRESET]
  name: 'OrientDB.ConnectionError [2]',
  code: 2,
  message: 'read ECONNRESET',
  data: {} }
Unhandled rejection OrientDB.ConnectionError [2]: read ECONNRESET
    at Connection.handleSocketError (<...>/node_modules/orientjs/lib/transport/binary/connection.js:296:63)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:442:13)
```

OrientDB server side log:
```
2015-09-20 08:35:02:550 CONFI Remote client connected from: OClientConnection [id=27, source=?, since=1442752502550] [OClientConnectionManager]
2015-09-20 08:35:02:598 CONFI Remote client connected from: OClientConnection [id=28, source=/127.0.0.1:40588, since=1442752502597] [OClientConnectionManager]
2015-09-20 08:35:02:598 FINE  Sent run-time exception to the client /127.0.0.1:40588: com.orientechnologies.orient.core.exception.OSecurityAccessException: Server user not authenticated. [ONetworkProtocolBinary]
2015-09-20 08:35:02:599 CONFI Remote client connected from: OClientConnection [id=29, source=/127.0.0.1:40588, since=1442752502599] [OClientConnectionManager]
2015-09-20 08:35:02:599 FINE  Sent run-time exception to the client /127.0.0.1:40588: com.orientechnologies.orient.core.exception.OSecurityAccessException: Server user not authenticated. [ONetworkProtocolBinary]
2015-09-20 08:35:02:599 FINE  Found unknown session 1648, shutdown current connection [ONetworkProtocolBinary]Error during closing of output stream
java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.DataOutputStream.flush(DataOutputStream.java:123)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.close(OChannelBinary.java:406)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.shutdown(OBinaryNetworkProtocolAbstract.java:114)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.shutdown(ONetworkProtocolBinary.java:148)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sendError(ONetworkProtocolBinary.java:879)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
	Suppressed: java.net.SocketException: Socket closed
		at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
		at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
		at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
		at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
		at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
		at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
		... 6 more
Error during channel flush
java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.DataOutputStream.flush(DataOutputStream.java:123)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.flush(OChannelBinary.java:387)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.handleConnectionError(OBinaryNetworkProtocolAbstract.java:402)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.handleConnectionError(ONetworkProtocolBinary.java:1851)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error during closing of output stream
java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.DataOutputStream.flush(DataOutputStream.java:123)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.close(OChannelBinary.java:406)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.shutdown(OBinaryNetworkProtocolAbstract.java:114)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.shutdown(ONetworkProtocolBinary.java:148)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:85)
	Suppressed: java.net.SocketException: Socket closed
		at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
		at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
		at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
		at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
		at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
		at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
		... 4 more
```


```
var config = require("../config")
var OrientDB = require('orientjs');

console.log("server: " + config.get("orientdb:host") + ":" + config.get("orientdb:port"))
console.log("server_username: " + config.get("orientdb:server_username"))
console.log("server_password: " + config.get("orientdb:server_password"))

var server = OrientDB({
  host: config.get("orientdb:host"),
  port: config.get("orientdb:port"),
  username: config.get("orientdb:server_username"),
  password: config.get("orientdb:server_password")//,
  //transport: "rest"
})

console.log("database: " + config.get("orientdb:db"))
console.log("db_username: " + config.get("orientdb:db_username"))
console.log("db_password: " + config.get("orientdb:db_password"))

var db = server.use({
  name: config.get("orientdb:db"),
  username: config.get("orientdb:db_username"),
  password: config.get("orientdb:db_password")
})

server.create({
  name: 'mydb',
  type: 'graph',
  storage: 'plocal'
})
.then(function (db) {
  console.log('Created a database called ' + db.name);
});

server.list()
.then(function (dbs) {
  console.log('There are ' + dbs.length + ' databases on the server.');
})
.catch(function (err){
  console.error(err)
});

console.log('Using OrientDB database: ' + db.name);
//server.close();

module.exports = {
    server: server,
    db: db
}
```

**Comment by ledgr** [comment]
I think I will stick to REST API.

**Comment by StarpTech** [comment]
@ledgr I use Orientjs with Orientdb 2.0.15 and all works fine. I would downgrade to 2.0.15 released september

**Comment by StarpTech** [comment]
```
"config": {
"orientdb": {
		"host": "localhost",
		"port": 2424,
		"enableRIDBags": false,
		"username": "XXXX",
		"password": "XXXX",
		"database": "test"
	}
}

	var server = require('orientjs')(config.orientdb);
	var db = server.use(config.orientdb.database);
```

**Comment by jbilcke** [comment]
I had the same issue, my solution is to create a second instance of the OrientJS client, dedicated to executing this kind of server level query (like "list databases"). 

Actually for my use case, doing so is also beneficial in term of architecture because my user can create multiple databases. Even if they delete, connect or disconnect multiple dbs while the app is running, the pipeline used to list them won't change
