### ISSUE TITLE
Rest transport backend broken (OrientJS v2.0.0 and v2.2.0)

### ISSUE THREAD

**Issue by ledgr** [orientechnologies/orientjs#96]
<...>/node_modules/orientjs/lib/transport/rest/index.js:101
    op = new operations\[op\](params || {});
             ^
TypeError: undefined is not a function
    at RestTransport.process (<...>/node_modules/orientjs/lib/transport/rest/index.js:101:10)
    at RestTransport.send (<...>/node_modules/orientjs/lib/transport/rest/index.js:81:15)
    at Server.send (<...>/node_modules/orientjs/lib/server/index.js:112:25)
    at Server.create (<...>/node_modules/orientjs/lib/server/index.js:204:15)
    at Object.<anonymous> (<...>/models/orientdb.js:23:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

```
var config = require("../config")
var OrientDB = require('orientjs');

var server = OrientDB({
  host: config.get("orientdb:host"),
  port: config.get("orientdb:port"),
  username: config.get("orientdb:server_username"),
  password: config.get("orientdb:server_password"),
  transport: "rest"
})
```

**Comment by lvca** [comment]
@ledgr why did you close it?
